name: nj_pizza_delivery
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  image_picker: ^1.2.1
  photo_manager: ^3.7.1
  flutter_spinkit: ^5.2.2
  country_state_city: ^0.1.6
  font_awesome_flutter: ^10.7.0
  permission_handler: ^11.3.0
  cached_network_image: ^3.2.3
  confetti: ^0.6.0
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
